export const RENDER_LOGO = "RENDER_LOGO";
export const RENDER_THEME = "RENDER_THEME";
export const SET_MEMBER_STATUS = "SET_MEMBER_STATUS";
export const SET_SEARCH_DATA = "SET_SEARCH_DATA";
export const SET_MOVIES_PAGE_CONTENT = "SET_MOVIES_PAGE_CONTENT";
export const SET_LIST_TRANSFORM = "SET_LIST_TRANSFORM";
